openapi: "3.0.0"
info:
  description: REST API for NLP.
  version: "1.0.0"
  title: REST API for NLP.

servers:
  - url: /api

paths:
  /process_sentences:
    get:
      operationId: nlp_processor.process_sentences
      tags:
        - Sentence
      summary: Get array of JSON objects for a sentence.
      description: Get array of JSON objects for a sentence
      parameters:
        - name: sentences_str
          in: query
          description: Sentences in a human language.
          schema:
            type: string
          required: True
      responses:
        200:
          description: Successfully processed input sentences.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sentences'

components:
  schemas:
    word:
      properties:
        text:
          type: string
        lemma:
          type: string
        pos:
          type: string
        index:
          type: integer
        feats:
          type: array
          items: {}
    sentence:
      type: array
      items:
        $ref: "#/components/schemas/word"
    sentences:
      type: array
      items:
        $ref: "#/components/schemas/sentence"
